#!/usr/bin/env bash

# Run commands from the theme folder.
cd ${PROJECT_ROOT}/${DOCROOT}/themes/custom/sandbox

echo "Initializing npm dependencies..."
npm install

echo "Compiling theme..."
./node_modules/.bin/gulp build
